import type { Metadata } from "next";
// import { Header } from "@/components/Header";
import "./globals.css";
import { Notifications } from "@/components/Notifications";
import { auth } from "@/auth";

import { BottomNavbar } from "@/components/HeaderTest";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FondFlow",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-zinc-100`}>
        <Notifications />
        {/* {session && <Header />} */}

        {!session && (
          <main className="flex flex-col items-center justify-center p-4 min-w-fit h-full w-dvh">
            {children}
          </main>
        )}

        {session && (
          <>
            <BottomNavbar />
            <main className="flex flex-col items-center p-4 h-fit w-full pt-14 overflow-x-scroll">
              {children}
            </main>
          </>
        )}
      </body>
    </html>
  );
}
