import type { Metadata, Viewport } from "next";

import "./globals.css";
import { Notifications } from "@/components/Notifications";
import { Providers } from "./providers";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Monevo",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-lightMain dark:bg-darkMain`}
      >
        <Providers>
          <Notifications />

          {children}
        </Providers>
      </body>
    </html>
  );
}
